writer1           = console
writer1.format    = {date: HH:mm:ss.SSS} {level}:\n{message}\n
writer1.level     = debug

writer2           = file
writer2.format    = {level}:\n{message}\n
writer2.file      = logs/LatestSession.log
writer2.charset   = UTF-8
writer2.buffered  = true
writer2.append    = false
writer2.level     = debug

writer3           = log queue
writer3.format    = {date: HH:mm:ss} {level}:\n{message}\n
writer3.level     = info

writingthread     = true